import { createHash } from "crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";

import { sanitizeAtom, sanitizeEnumAtom, sanitizeStrictId } from "./sanitize.mjs";

export const ACTIVE_ONTOLOGY_RELATIVE_PATH = join("reports", "ontology", "project.ttl");
export const ACTIVE_ONTOLOGY_INTEGRITY_RELATIVE_PATH = join("reports", "ontology", "project.ttl.sha256.json");
export const ACTIVE_ONTOLOGY_SCHEMA_VERSION = 1;

const PREFIXES = Object.freeze([
  ["rdf", "http://www.w3.org/1999/02/22-rdf-syntax-ns#"],
  ["rdfs", "http://www.w3.org/2000/01/rdf-schema#"],
  ["owl", "http://www.w3.org/2002/07/owl#"],
  ["xsd", "http://www.w3.org/2001/XMLSchema#"],
  ["p", "http://iterative-planner.dev/project/"],
  ["req", "http://iterative-planner.dev/requirements/"],
  ["impl", "http://iterative-planner.dev/implementation/"],
  ["audit", "http://iterative-planner.dev/audit/"],
  ["ml", "http://iterative-planner.dev/ml/"],
  ["prod", "http://iterative-planner.dev/product/"],
  ["ux", "http://iterative-planner.dev/ux/"],
  ["prov", "http://iterative-planner.dev/provenance/"],
]);

const ALLOWED_PREFIXES = new Set(PREFIXES.map(([prefix]) => prefix));
const DEFAULT_WRITER = "ontology_write.mjs";

function nowIso(now = new Date()) {
  return now instanceof Date ? now.toISOString() : new Date(now).toISOString();
}

function ensureParent(filePath) {
  mkdirSync(dirname(filePath), { recursive: true });
}

function sha256Text(text) {
  return createHash("sha256").update(String(text || ""), "utf-8").digest("hex");
}

function readTextIfPresent(path) {
  return existsSync(path) ? readFileSync(path, "utf-8") : null;
}

function jsonLiteral(value) {
  return JSON.stringify(String(value ?? ""));
}

function literalTerm(value, datatype = "xsd:string") {
  const normalizedDatatype = normalizeDatatype(datatype);
  return `${jsonLiteral(value)}^^${normalizedDatatype}`;
}

function normalizeDatatype(value) {
  const datatype = String(value || "xsd:string").trim();
  if (!/^[a-z][a-z0-9_-]*:[A-Za-z][A-Za-z0-9_-]*$/.test(datatype)) {
    throw new Error(`invalid datatype term: ${datatype}`);
  }
  const prefix = datatype.split(":")[0];
  if (!ALLOWED_PREFIXES.has(prefix)) throw new Error(`unsupported datatype prefix: ${prefix}`);
  return datatype;
}

function normalizeResourceTerm(value, { allowTypePredicate = false } = {}) {
  const term = String(value || "").trim();
  if (allowTypePredicate && term === "a") return term;
  if (/^<[A-Za-z][A-Za-z0-9+.-]*:\/\/[^>\s]+>$/.test(term)) return term;
  if (!/^[a-z][a-z0-9_-]*:[A-Za-z0-9][A-Za-z0-9_.-]*$/.test(term)) {
    throw new Error(`invalid resource term: ${term}`);
  }
  const prefix = term.split(":")[0];
  if (!ALLOWED_PREFIXES.has(prefix)) throw new Error(`unsupported prefix: ${prefix}`);
  return term;
}

function normalizeEnumResource(value, fallback) {
  const raw = String(value || fallback).trim();
  return raw.includes(":") ? normalizeResourceTerm(raw) : normalizeResourceTerm(`prov:${raw}`);
}

function normalizeObjectTerm(operation) {
  const kind = String(operation.objectKind || operation.object_kind || "iri").trim().toLowerCase();
  if (kind === "literal") {
    return {
      object_kind: "literal",
      object_value: String(operation.object ?? ""),
      object_term: literalTerm(operation.object, operation.datatype || "xsd:string"),
      datatype: normalizeDatatype(operation.datatype || "xsd:string"),
    };
  }
  return {
    object_kind: "iri",
    object_value: normalizeResourceTerm(operation.object),
    object_term: normalizeResourceTerm(operation.object),
    datatype: null,
  };
}

function normalizeOperation(operation) {
  const action = String(operation.operation || operation.op || "add").trim().toLowerCase();
  if (!["add", "retract"].includes(action)) throw new Error(`unsupported operation: ${action}`);
  const object = normalizeObjectTerm(operation);
  return {
    operation: action,
    subject: normalizeResourceTerm(operation.subject),
    predicate: normalizeResourceTerm(operation.predicate),
    ...object,
    source_ref: String(operation.sourceRef || operation.source_ref || "").trim(),
    reason: String(operation.reason || operation.retractedReason || operation.retracted_reason || "").trim(),
  };
}

function renderHeader() {
  return [
    "# Generated by iterative-planner active ontology writer.",
    "# Do not edit manually; use ontology_write.mjs so the sidecar hash stays valid.",
    ...PREFIXES.map(([prefix, iri]) => `@prefix ${prefix}: <${iri}> .`),
    "",
  ].join("\n");
}

function renderTriple(subject, predicate, object) {
  return `${subject} ${predicate} ${object} .`;
}

function renderTriples(triples) {
  return triples.map((triple) => renderTriple(triple.subject, triple.predicate, triple.object)).join("\n") + "\n";
}

function termLocalId(term) {
  return String(term || "").replace(/^p:/, "");
}

function tripleKey(subject, predicate, objectTerm) {
  return `${subject}\u0000${predicate}\u0000${objectTerm}`;
}

function parseObjectTerm(raw) {
  const value = String(raw || "").trim();
  const literalMatch = value.match(/^"((?:\\.|[^"\\])*)"(?:\^\^([a-z][a-z0-9_-]*:[A-Za-z][A-Za-z0-9_-]*))?$/);
  if (literalMatch) {
    return {
      kind: "literal",
      value: JSON.parse(`"${literalMatch[1]}"`),
      datatype: literalMatch[2] || "xsd:string",
      term: value,
    };
  }
  return { kind: "iri", value, datatype: null, term: value };
}

function objectFactValue(term) {
  const parsed = parseObjectTerm(term);
  return parsed.value;
}

function objectFactKind(term) {
  return parseObjectTerm(term).kind;
}

function objectFactAtom(term) {
  const parsed = parseObjectTerm(term);
  return parsed.kind === "iri" ? sanitizeStrictId(parsed.value) : sanitizeAtom(parsed.value);
}

function parseTripleLine(line, index) {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith("#") || trimmed.startsWith("@prefix")) return null;
  const match = trimmed.match(/^(\S+)\s+(\S+)\s+(.+)\s+\.$/);
  if (!match) {
    return { issue: `line ${index + 1}: unsupported Turtle syntax outside canonical writer subset` };
  }
  const [, subject, predicate, object] = match;
  return { subject, predicate, object: object.trim(), line: index + 1 };
}

function subjectRecord(records, subject) {
  if (!records.has(subject)) records.set(subject, {});
  return records.get(subject);
}

export function getActiveOntologyPath(cwd = process.cwd()) {
  return join(cwd, ACTIVE_ONTOLOGY_RELATIVE_PATH);
}

export function getActiveOntologyIntegrityPath(cwd = process.cwd()) {
  return join(cwd, ACTIVE_ONTOLOGY_INTEGRITY_RELATIVE_PATH);
}

export function computeActiveOntologyDigest({ cwd = process.cwd() } = {}) {
  const path = getActiveOntologyPath(cwd);
  const content = readTextIfPresent(path);
  if (content === null) return null;
  return sha256Text(content);
}

export function initializeActiveOntology({ cwd = process.cwd(), now = new Date() } = {}) {
  const path = getActiveOntologyPath(cwd);
  if (!existsSync(path)) {
    ensureParent(path);
    writeFileSync(path, renderHeader());
  }
  return writeActiveOntologyIntegrity({ cwd, now });
}

export function readActiveOntologyIntegrity({ cwd = process.cwd() } = {}) {
  const path = getActiveOntologyIntegrityPath(cwd);
  if (!existsSync(path)) return null;
  try {
    return JSON.parse(readFileSync(path, "utf-8"));
  } catch {
    return null;
  }
}

export function writeActiveOntologyIntegrity({ cwd = process.cwd(), now = new Date() } = {}) {
  const ontologyPath = getActiveOntologyPath(cwd);
  const integrityPath = getActiveOntologyIntegrityPath(cwd);
  if (!existsSync(ontologyPath)) {
    return { ok: false, status: "MISSING", issues: ["project.ttl missing"], path: ontologyPath, integrity_path: integrityPath };
  }
  const digest = computeActiveOntologyDigest({ cwd });
  const record = {
    schema_version: ACTIVE_ONTOLOGY_SCHEMA_VERSION,
    path: ACTIVE_ONTOLOGY_RELATIVE_PATH.replace(/\\/g, "/"),
    sha256: digest,
    writer: DEFAULT_WRITER,
    updated_at: nowIso(now),
  };
  ensureParent(integrityPath);
  writeFileSync(integrityPath, JSON.stringify(record, null, 2) + "\n");
  return { ok: true, status: "PASS", digest, path: ontologyPath, integrity_path: integrityPath, record };
}

export function validateActiveOntology({ cwd = process.cwd(), allowMissing = false } = {}) {
  const path = getActiveOntologyPath(cwd);
  const integrityPath = getActiveOntologyIntegrityPath(cwd);
  if (!existsSync(path)) {
    return { ok: !!allowMissing, status: "MISSING", issues: ["project.ttl missing"], path, integrity_path: integrityPath };
  }
  if (!existsSync(integrityPath)) {
    return { ok: false, status: "FAIL", code: "active_ontology_integrity_missing", issues: ["integrity sidecar missing"], path, integrity_path: integrityPath };
  }
  const integrity = readActiveOntologyIntegrity({ cwd });
  if (!integrity || integrity.schema_version !== ACTIVE_ONTOLOGY_SCHEMA_VERSION || typeof integrity.sha256 !== "string") {
    return { ok: false, status: "FAIL", code: "active_ontology_integrity_invalid", issues: ["integrity sidecar is invalid"], path, integrity_path: integrityPath };
  }
  const digest = computeActiveOntologyDigest({ cwd });
  if (digest !== integrity.sha256) {
    return {
      ok: false,
      status: "FAIL",
      code: "active_ontology_integrity_mismatch",
      issues: [`project.ttl digest mismatch (expected ${integrity.sha256}, got ${digest})`],
      digest,
      expected_digest: integrity.sha256,
      path,
      integrity_path: integrityPath,
    };
  }
  const parsed = parseActiveOntology({ cwd, validateIntegrity: false });
  if (!parsed.ok) return { ...parsed, path, integrity_path: integrityPath };
  return { ok: true, status: "PASS", digest, path, integrity_path: integrityPath, parsed };
}

export function parseActiveOntology({ cwd = process.cwd(), validateIntegrity = true } = {}) {
  if (validateIntegrity) {
    const validation = validateActiveOntology({ cwd });
    if (!validation.ok) return validation;
  }

  const path = getActiveOntologyPath(cwd);
  if (!existsSync(path)) return { ok: false, status: "MISSING", issues: ["project.ttl missing"], path };
  const content = readFileSync(path, "utf-8");
  const issues = [];
  const triples = [];

  content.split("\n").forEach((line, index) => {
    const parsed = parseTripleLine(line, index);
    if (!parsed) return;
    if (parsed.issue) issues.push(parsed.issue);
    else triples.push(parsed);
  });

  const records = new Map();
  for (const triple of triples) {
    const record = subjectRecord(records, triple.subject);
    if (!record[triple.predicate]) record[triple.predicate] = [];
    record[triple.predicate].push(triple.object);
  }

  const iterations = [];
  const deltas = [];
  const statements = [];

  for (const [subject, record] of records.entries()) {
    const types = new Set(record.a || []);
    if (types.has("prov:Iteration")) {
      iterations.push({
        id: subject,
        iteration_number: Number.parseInt(objectFactValue(record["prov:iterationNumber"]?.[0]), 10),
        plan_id: objectFactValue(record["prov:planId"]?.[0] || "\"ad-hoc\"^^xsd:string"),
        trigger: record["prov:trigger"]?.[0] || null,
        phase: record["prov:phase"]?.[0] || null,
        writer: objectFactValue(record["prov:writer"]?.[0] || `"${DEFAULT_WRITER}"^^xsd:string`),
        add_count: Number.parseInt(objectFactValue(record["prov:tripleAddCount"]?.[0] || "\"0\"^^xsd:integer"), 10) || 0,
        retract_count: Number.parseInt(objectFactValue(record["prov:tripleRetractCount"]?.[0] || "\"0\"^^xsd:integer"), 10) || 0,
      });
    }
    if (types.has("prov:OntologyDelta")) {
      deltas.push({
        id: subject,
        operation: record["prov:operation"]?.[0] || null,
        iteration_id: record["prov:forIteration"]?.[0] || null,
        subject: record["prov:subject"]?.[0] || null,
        predicate: record["prov:predicate"]?.[0] || null,
        object_term: record["prov:object"]?.[0] || null,
        object_kind: record["prov:objectKind"] ? objectFactValue(record["prov:objectKind"][0]) : null,
        writer: record["prov:writer"] ? objectFactValue(record["prov:writer"][0]) : null,
        source_ref: record["prov:sourceRef"] ? objectFactValue(record["prov:sourceRef"][0]) : null,
      });
    }
    if (types.has("rdf:Statement")) {
      const objectTerm = record["rdf:object"]?.[0] || null;
      statements.push({
        id: subject,
        subject: record["rdf:subject"]?.[0] || null,
        predicate: record["rdf:predicate"]?.[0] || null,
        object_term: objectTerm,
        object_kind: objectTerm ? objectFactKind(objectTerm) : null,
        added_in_iteration: record["prov:addedInIteration"]?.[0] || null,
        retracted_in_iteration: record["prov:retractedInIteration"]?.[0] || null,
      });
    }
  }

  for (const statement of statements) {
    if (!statement.subject || !statement.predicate || !statement.object_term || !statement.added_in_iteration) {
      issues.push(`statement ${statement.id} is missing subject, predicate, object, or added iteration`);
    }
  }

  if (issues.length > 0) return { ok: false, status: "FAIL", code: "active_ontology_parse_failed", issues, path };

  const current = statements.filter((statement) => !statement.retracted_in_iteration);
  return {
    ok: true,
    status: "PASS",
    path,
    digest: computeActiveOntologyDigest({ cwd }),
    triples,
    iterations: iterations.sort((left, right) => left.iteration_number - right.iteration_number),
    deltas: deltas.sort((left, right) => left.id.localeCompare(right.id)),
    statements: statements.sort((left, right) => left.id.localeCompare(right.id)),
    current_statements: current.sort((left, right) => left.id.localeCompare(right.id)),
  };
}

export function appendActiveOntologyDelta({
  cwd = process.cwd(),
  operations = [],
  planId = "ad-hoc",
  trigger = "ManualRepair",
  gate = null,
  sessionId = process.env.CODEX_THREAD_ID || "unknown",
  writer = DEFAULT_WRITER,
  phase = "AdHoc",
  gateVerdict = "NotApplicable",
  addedBy = "planner",
  sourceRef = "manual",
  expectDigest = null,
  now = new Date(),
} = {}) {
  initializeActiveOntology({ cwd, now });
  const beforeDigest = computeActiveOntologyDigest({ cwd });
  if (expectDigest && expectDigest !== beforeDigest) {
    return {
      ok: false,
      status: "FAIL",
      code: "active_ontology_stale_write",
      digest: beforeDigest,
      expected_digest: expectDigest,
      issues: [`stale active ontology digest (expected ${expectDigest}, got ${beforeDigest})`],
    };
  }

  const validation = validateActiveOntology({ cwd });
  if (!validation.ok) return validation;

  let normalized;
  try {
    normalized = operations.map((operation) => normalizeOperation(operation));
  } catch (error) {
    return { ok: false, status: "FAIL", code: "active_ontology_invalid_operation", issues: [error.message] };
  }
  if (normalized.length === 0) {
    return { ok: false, status: "FAIL", code: "active_ontology_no_operations", issues: ["at least one operation is required"] };
  }

  const parsed = parseActiveOntology({ cwd });
  if (!parsed.ok) return parsed;
  const currentByKey = new Map(parsed.current_statements.map((statement) =>
    [tripleKey(statement.subject, statement.predicate, statement.object_term), statement]
  ));

  for (const operation of normalized) {
    const key = tripleKey(operation.subject, operation.predicate, operation.object_term);
    if (operation.operation === "add" && currentByKey.has(key)) {
      return { ok: false, status: "FAIL", code: "active_ontology_duplicate_current_triple", issues: [`current triple already exists: ${operation.subject} ${operation.predicate} ${operation.object_term}`] };
    }
    if (operation.operation === "retract" && !currentByKey.has(key)) {
      return { ok: false, status: "FAIL", code: "active_ontology_retract_missing_triple", issues: [`cannot retract missing current triple: ${operation.subject} ${operation.predicate} ${operation.object_term}`] };
    }
  }

  const nextNumber = Math.max(0, ...parsed.iterations.map((iteration) => Number(iteration.iteration_number) || 0)) + 1;
  const padded = String(nextNumber).padStart(3, "0");
  const iterationId = `p:ITR-${padded}`;
  const timestamp = nowIso(now);
  const addCount = normalized.filter((operation) => operation.operation === "add").length;
  const retractCount = normalized.filter((operation) => operation.operation === "retract").length;
  const block = [];

  block.push("");
  block.push(`# iteration ${padded}`);
  block.push(renderTriple(iterationId, "a", "prov:Iteration"));
  block.push(renderTriple(iterationId, "prov:iterationNumber", literalTerm(nextNumber, "xsd:integer")));
  block.push(renderTriple(iterationId, "prov:planId", literalTerm(planId)));
  block.push(renderTriple(iterationId, "prov:trigger", normalizeEnumResource(trigger, "ManualRepair")));
  if (gate) block.push(renderTriple(iterationId, "prov:gate", literalTerm(gate)));
  block.push(renderTriple(iterationId, "prov:sessionId", literalTerm(sessionId)));
  block.push(renderTriple(iterationId, "prov:writer", literalTerm(writer)));
  block.push(renderTriple(iterationId, "prov:phase", normalizeEnumResource(phase, "AdHoc")));
  block.push(renderTriple(iterationId, "prov:startedAt", literalTerm(timestamp, "xsd:dateTime")));
  block.push(renderTriple(iterationId, "prov:closedAt", literalTerm(timestamp, "xsd:dateTime")));
  block.push(renderTriple(iterationId, "prov:tripleAddCount", literalTerm(addCount, "xsd:integer")));
  block.push(renderTriple(iterationId, "prov:tripleRetractCount", literalTerm(retractCount, "xsd:integer")));
  block.push(renderTriple(iterationId, "prov:gateVerdict", normalizeEnumResource(gateVerdict, "NotApplicable")));

  const deltas = [];
  normalized.forEach((operation, index) => {
    const deltaId = `p:DELTA-ITR-${padded}-${String(index + 1).padStart(3, "0")}`;
    const statementId = operation.operation === "add"
      ? `p:STMT-ITR-${padded}-${String(index + 1).padStart(3, "0")}`
      : currentByKey.get(tripleKey(operation.subject, operation.predicate, operation.object_term)).id;
    const operationTerm = operation.operation === "add" ? "prov:AddAssertion" : "prov:RetractAssertion";

    block.push("");
    block.push(renderTriple(deltaId, "a", "prov:OntologyDelta"));
    block.push(renderTriple(deltaId, "prov:operation", operationTerm));
    block.push(renderTriple(deltaId, "prov:forIteration", iterationId));
    block.push(renderTriple(deltaId, "prov:subject", operation.subject));
    block.push(renderTriple(deltaId, "prov:predicate", operation.predicate));
    block.push(renderTriple(deltaId, "prov:object", operation.object_term));
    block.push(renderTriple(deltaId, "prov:objectKind", literalTerm(operation.object_kind)));
    block.push(renderTriple(deltaId, "prov:addedBy", literalTerm(addedBy)));
    block.push(renderTriple(deltaId, "prov:sourceRef", literalTerm(operation.source_ref || sourceRef)));
    block.push(renderTriple(deltaId, "prov:writer", literalTerm(writer)));
    block.push(renderTriple(deltaId, "prov:phase", normalizeEnumResource(phase, "AdHoc")));
    if (operation.operation === "retract") {
      block.push(renderTriple(deltaId, "prov:retractedReason", literalTerm(operation.reason || "not specified")));
    }

    if (operation.operation === "add") {
      block.push("");
      block.push(renderTriple(operation.subject, operation.predicate, operation.object_term));
      block.push(renderTriple(statementId, "a", "rdf:Statement"));
      block.push(renderTriple(statementId, "rdf:subject", operation.subject));
      block.push(renderTriple(statementId, "rdf:predicate", operation.predicate));
      block.push(renderTriple(statementId, "rdf:object", operation.object_term));
      block.push(renderTriple(statementId, "prov:addedInIteration", iterationId));
      currentByKey.set(tripleKey(operation.subject, operation.predicate, operation.object_term), {
        id: statementId,
        subject: operation.subject,
        predicate: operation.predicate,
        object_term: operation.object_term,
      });
    } else {
      block.push(renderTriple(statementId, "prov:retractedInIteration", iterationId));
      currentByKey.delete(tripleKey(operation.subject, operation.predicate, operation.object_term));
    }

    deltas.push({
      id: deltaId,
      operation: operation.operation,
      statement_id: statementId,
      subject: operation.subject,
      predicate: operation.predicate,
      object: objectFactValue(operation.object_term),
      object_kind: operation.object_kind,
    });
  });

  const path = getActiveOntologyPath(cwd);
  const content = readFileSync(path, "utf-8").replace(/\n*$/, "\n") + block.join("\n") + "\n";
  writeFileSync(path, content);
  const integrity = writeActiveOntologyIntegrity({ cwd, now });
  return {
    ok: true,
    status: "PASS",
    path,
    integrity_path: getActiveOntologyIntegrityPath(cwd),
    digest_before: beforeDigest,
    digest_after: integrity.digest,
    iteration_id: iterationId,
    iteration_number: nextNumber,
    add_count: addCount,
    retract_count: retractCount,
    deltas,
  };
}

export function compileActiveOntologyFacts({ cwd = process.cwd(), requireIntegrity = true } = {}) {
  const parsed = parseActiveOntology({ cwd, validateIntegrity: requireIntegrity });
  if (!parsed.ok) {
    if (parsed.status === "MISSING") {
      return { ok: false, status: "MISSING", facts: ["active_ontology_present(false)."], issues: parsed.issues || [] };
    }
    const facts = [
      "active_ontology_present(true).",
      `active_ontology_integrity_status(${sanitizeEnumAtom("fail")}).`,
      ...(parsed.issues || []).map((issue) => `active_ontology_issue(${sanitizeAtom(issue)}).`),
    ];
    return { ok: false, status: "FAIL", facts, issues: parsed.issues || [] };
  }

  const facts = [
    "active_ontology_present(true).",
    `active_ontology_integrity_status(${sanitizeEnumAtom("pass")}).`,
    `active_ontology_digest(${sanitizeAtom(parsed.digest)}).`,
  ];

  for (const iteration of parsed.iterations) {
    facts.push(`active_ontology_iteration(${sanitizeStrictId(termLocalId(iteration.id))}, ${Number(iteration.iteration_number) || 0}, ${sanitizeAtom(iteration.plan_id)}, ${sanitizeEnumAtom(termLocalId(iteration.trigger))}, ${sanitizeEnumAtom(termLocalId(iteration.phase))}, ${sanitizeAtom(iteration.writer)}).`);
  }

  for (const statement of parsed.statements) {
    facts.push(`active_ontology_triple(${sanitizeStrictId(statement.subject)}, ${sanitizeStrictId(statement.predicate)}, ${objectFactAtom(statement.object_term)}, ${sanitizeEnumAtom(statement.object_kind)}, ${sanitizeStrictId(termLocalId(statement.added_in_iteration))}).`);
  }

  for (const statement of parsed.current_statements) {
    facts.push(`active_ontology_current(${sanitizeStrictId(statement.subject)}, ${sanitizeStrictId(statement.predicate)}, ${objectFactAtom(statement.object_term)}).`);
  }

  for (const delta of parsed.deltas) {
    facts.push(`active_ontology_delta(${sanitizeStrictId(termLocalId(delta.id))}, ${sanitizeEnumAtom(termLocalId(delta.operation))}, ${sanitizeStrictId(termLocalId(delta.iteration_id))}, ${sanitizeStrictId(delta.subject)}, ${sanitizeStrictId(delta.predicate)}, ${objectFactAtom(delta.object_term)}, ${sanitizeEnumAtom(delta.object_kind || objectFactKind(delta.object_term))}).`);
  }

  return { ok: true, status: "PASS", facts, parsed, issues: [] };
}
