#!/usr/bin/env node
// test_annotation_discipline_gate.mjs - Phase A.4 regression coverage for
// proactive-ontology proposal: lock the @planner annotation discipline gate
// (GATE-PLN-ANN-001) emitted by gatePlanToExecute.
//
// Covers:
//   - File with @planner annotations    -> PASS
//   - File without annotations           -> FAIL
//   - Substantive waiver in plan.md      -> PASS
//   - Placeholder waiver reason (TBD)    -> FAIL (waiver placeholder rejected)
//   - File not yet on disk               -> SKIP (pre-EXECUTE)
//   - Non-worthy path (e.g., docs/)      -> no result emitted
//   - PLANNER_ANNOTATION_DISCIPLINE=off  -> WARN (advisory mode)
//   - Plan with no worthy files          -> no result emitted

import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from "fs";
import { join } from "path";
import { tmpdir } from "os";

import {
  analyzeAnnotationDiscipline,
  parseAnnotationWaivers,
  isAnnotationDisciplineEnabled,
} from "../scripts/lib/annotation_discipline.mjs";

let passed = 0;
let failed = 0;

function assert(cond, label) {
  if (cond) { passed += 1; console.log(`  PASS: ${label}`); }
  else { failed += 1; console.log(`  FAIL: ${label}`); }
}

function makeFixture(prefix, files) {
  // files = { "scripts/foo.mjs": "...contents..." }
  const root = mkdtempSync(join(tmpdir(), `ann-discipline-${prefix}-`));
  for (const [relPath, content] of Object.entries(files || {})) {
    const abs = join(root, relPath);
    mkdirSync(join(abs, ".."), { recursive: true });
    writeFileSync(abs, content);
  }
  return root;
}

console.log("\nAnnotation Discipline Gate (GATE-PLN-ANN-001) Regression\n");

// ──────────────────────────────────────────────────────────────────────
// Scenario 1: File with valid @planner annotations -> PASS
// ──────────────────────────────────────────────────────────────────────
{
  const cwd = makeFixture("ann-pass", {
    "scripts/sample.mjs": "// @planner:capability = sample_thing\nexport const ok = true;\n",
  });
  try {
    const plan = "## Files To Modify\n- scripts/sample.mjs\n";
    const r = analyzeAnnotationDiscipline({ planContent: plan, cwd });
    assert(r.required === true, "annotation-worthy file makes discipline 'required'");
    assert(r.satisfied === true, "annotated file PASSes");
    assert(r.violations.length === 0, "no violations recorded");
  } finally { try { rmSync(cwd, { recursive: true, force: true }); } catch {} }
}

// ──────────────────────────────────────────────────────────────────────
// Scenario 2: File without annotations and no waiver -> FAIL
// ──────────────────────────────────────────────────────────────────────
{
  const cwd = makeFixture("ann-fail", {
    "scripts/unannotated.mjs": "export const value = 42;\n",
  });
  try {
    const plan = "## Files To Modify\n- scripts/unannotated.mjs\n";
    const r = analyzeAnnotationDiscipline({ planContent: plan, cwd });
    assert(r.satisfied === false, "unannotated file FAILs the gate");
    assert(r.violations.length === 1, "one violation captured");
    assert(r.violations[0].kind === "missing_annotation", "violation kind is missing_annotation");
    assert(r.violations[0].path === "scripts/unannotated.mjs", "violation cites the offending file");
  } finally { try { rmSync(cwd, { recursive: true, force: true }); } catch {} }
}

// ──────────────────────────────────────────────────────────────────────
// Scenario 3: Substantive waiver lifts the requirement -> PASS
// ──────────────────────────────────────────────────────────────────────
{
  const cwd = makeFixture("ann-waiver", {
    "scripts/generated.mjs": "// generated\nexport default {};\n",
  });
  try {
    const plan = [
      "## Files To Modify",
      "- scripts/generated.mjs",
      "",
      "## Notes",
      "[KB_NOT_APPLICABLE: annotation: scripts/generated.mjs: build artifact regenerated by codegen; should not carry @planner annotations]",
    ].join("\n");
    const r = analyzeAnnotationDiscipline({ planContent: plan, cwd });
    assert(r.satisfied === true, "valid waiver lifts the requirement");
    assert(r.waivers.size === 1, "waiver parsed");
    const waiver = r.waivers.get("scripts/generated.mjs");
    assert(waiver && waiver.placeholder === false, "waiver reason is not a placeholder");
  } finally { try { rmSync(cwd, { recursive: true, force: true }); } catch {} }
}

// ──────────────────────────────────────────────────────────────────────
// Scenario 4: Placeholder waiver reason -> FAIL (rubber-stamp defense)
// ──────────────────────────────────────────────────────────────────────
{
  const cwd = makeFixture("ann-waiver-tbd", {
    "scripts/whatever.mjs": "export const v = 1;\n",
  });
  try {
    // Every placeholder pattern listed by WAIVER_REASON_PLACEHOLDER_PATTERNS
    // must be caught. Test the three highest-value: TBD, <placeholder>, [FILL].
    for (const reason of ["TBD", "<placeholder reason>", "[FILL: write reason]"]) {
      const plan = [
        "## Files To Modify",
        "- scripts/whatever.mjs",
        "",
        `[KB_NOT_APPLICABLE: annotation: scripts/whatever.mjs: ${reason}]`,
      ].join("\n");
      const r = analyzeAnnotationDiscipline({ planContent: plan, cwd });
      assert(r.satisfied === false, `placeholder waiver reason '${reason}' FAILs the gate`);
      assert(r.violations[0]?.kind === "waiver_placeholder", `kind=waiver_placeholder for '${reason}'`);
    }
  } finally { try { rmSync(cwd, { recursive: true, force: true }); } catch {} }
}

// ──────────────────────────────────────────────────────────────────────
// Scenario 5: File listed in plan but doesn't exist yet -> SKIP
// (pre-EXECUTE; the file hasn't been written yet, so the gate is patient)
// ──────────────────────────────────────────────────────────────────────
{
  const cwd = makeFixture("ann-not-yet-written", {});
  try {
    const plan = "## Files To Modify\n- scripts/future_helper.mjs\n";
    const r = analyzeAnnotationDiscipline({ planContent: plan, cwd });
    assert(r.required === true, "annotation-worthy path keeps required=true even when file is missing");
    assert(r.satisfied === true, "absent file SKIPped (no annotation check possible yet)");
    assert(r.violations.length === 0, "no violation while file doesn't exist on disk");
  } finally { try { rmSync(cwd, { recursive: true, force: true }); } catch {} }
}

// ──────────────────────────────────────────────────────────────────────
// Scenario 6: Non-worthy path (docs/, tests/fixtures/, etc.) -> no requirement
// ──────────────────────────────────────────────────────────────────────
{
  const cwd = makeFixture("ann-non-worthy", {
    "docs/README.md": "# Docs\n",
    "tests/fixtures/sample.json": "{}",
  });
  try {
    const plan = [
      "## Files To Modify",
      "- docs/README.md",
      "- tests/fixtures/sample.json",
    ].join("\n");
    const r = analyzeAnnotationDiscipline({ planContent: plan, cwd });
    assert(r.required === false, "non-worthy paths produce required=false");
    assert(r.satisfied === true, "no annotation-worthy files -> trivially satisfied");
  } finally { try { rmSync(cwd, { recursive: true, force: true }); } catch {} }
}

// ──────────────────────────────────────────────────────────────────────
// Scenario 7: PLANNER_ANNOTATION_DISCIPLINE=off -> WARN (advisory)
// ──────────────────────────────────────────────────────────────────────
{
  const cwd = makeFixture("ann-disabled", {
    "scripts/skipped.mjs": "export const v = 1;\n",
  });
  try {
    const plan = "## Files To Modify\n- scripts/skipped.mjs\n";
    const r = analyzeAnnotationDiscipline({
      planContent: plan,
      cwd,
      env: { PLANNER_ANNOTATION_DISCIPLINE: "off" },
    });
    assert(r.enabled === false, "PLANNER_ANNOTATION_DISCIPLINE=off disables enforcement");
    assert(r.satisfied === true, "advisory mode does not FAIL the gate");
    assert(r.required === true, "advisory mode still flags annotation-worthy files (so verify_gate emits WARN)");
  } finally { try { rmSync(cwd, { recursive: true, force: true }); } catch {} }
}

// ──────────────────────────────────────────────────────────────────────
// Scenario 8: Plan with no Files To Modify section -> no requirement, no fail
// ──────────────────────────────────────────────────────────────────────
{
  const cwd = makeFixture("ann-empty-plan", {});
  try {
    const plan = "# Plan v0\n\nThis plan has no Files To Modify section.\n";
    const r = analyzeAnnotationDiscipline({ planContent: plan, cwd });
    assert(r.required === false, "empty plan emits no requirement");
    assert(r.satisfied === true, "empty plan trivially satisfied");
    assert(r.planned.length === 0, "no planned files");
  } finally { try { rmSync(cwd, { recursive: true, force: true }); } catch {} }
}

// ──────────────────────────────────────────────────────────────────────
// Scenario 9: parseAnnotationWaivers parses + flags placeholder reasons
// ──────────────────────────────────────────────────────────────────────
{
  const plan = [
    "[KB_NOT_APPLICABLE: annotation: a.mjs: real reason here]",
    "[KB_NOT_APPLICABLE: annotation: b.mjs: TBD]",
    "[KB_NOT_APPLICABLE: annotation: c.mjs: <placeholder>]",
    "[KB_NOT_APPLICABLE: annotation: d.mjs: [FILL: text]]",
  ].join("\n");
  const waivers = parseAnnotationWaivers(plan);
  assert(waivers.size === 4, "all four waivers parsed");
  assert(waivers.get("a.mjs")?.placeholder === false, "real reason not flagged as placeholder");
  assert(waivers.get("b.mjs")?.placeholder === true, "TBD flagged as placeholder");
  assert(waivers.get("c.mjs")?.placeholder === true, "<placeholder> flagged as placeholder");
  assert(waivers.get("d.mjs")?.placeholder === true, "[FILL: ...] flagged as placeholder");
}

// ──────────────────────────────────────────────────────────────────────
// Scenario 10: isAnnotationDisciplineEnabled env parsing
// ──────────────────────────────────────────────────────────────────────
{
  assert(isAnnotationDisciplineEnabled({}) === true, "default is enabled");
  assert(isAnnotationDisciplineEnabled({ PLANNER_ANNOTATION_DISCIPLINE: "off" }) === false, "'off' disables");
  assert(isAnnotationDisciplineEnabled({ PLANNER_ANNOTATION_DISCIPLINE: "0" }) === false, "'0' disables");
  assert(isAnnotationDisciplineEnabled({ PLANNER_ANNOTATION_DISCIPLINE: "false" }) === false, "'false' disables");
  assert(isAnnotationDisciplineEnabled({ PLANNER_ANNOTATION_DISCIPLINE: "no" }) === false, "'no' disables");
  assert(isAnnotationDisciplineEnabled({ PLANNER_ANNOTATION_DISCIPLINE: "on" }) === true, "'on' enabled");
}

console.log(`\nResults: ${passed} passed, ${failed} failed`);
process.exit(failed > 0 ? 1 : 0);
